version: '3.8'

services:
  memes-generator:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8080
      - WEB_ROOT=./web/build
      - DATA_DIR=./data
      - GENERATE_MEME_MODE=default
      - CLOUDRU_GENERATE_MEME_JOB_NAME=generate-meme-job
      - CLOUDRU_PROJECT_ID=